run:
  timeout: 5m
  modules-download-mode: readonly
  go: '1.26'

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - depguard
    - misspell
    - nolintlint
    - gofmt
    - goimports
    - goconst
    - bodyclose

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
  
  depguard:
    rules:
      domain:
        files:
          - "**/internal/core/domain/**"
        allow:
          - "$gostd"
          - "github.com/dev-igorcarvalho/don/pkg"
          - "github.com/dev-igorcarvalho/don/internal/core/domain"
      
      usecases:
        files:
          - "**/internal/core/usecases/**"
        allow:
          - "$gostd"
          - "github.com/dev-igorcarvalho/don/pkg"
          - "github.com/dev-igorcarvalho/don/internal/core/domain"
          - "github.com/dev-igorcarvalho/don/internal/core/usecases"
      
      pkg:
        files:
          - "**/pkg/**"
        deny:
          - pkg: "github.com/dev-igorcarvalho/don/internal"
            desc: "Package layer (pkg) cannot depend on internal application logic"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
